# Welcome to Jekyll!
#

# Site settings
title: Edward Woodcock
description: |
  Ruby on Rails | NodeJS | AWS | Full-stack
owner: Edward Woodcock # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ed@edwardwoodcock.com
baseurl: "/edwardwoodcock.com" # the subpath of your site, e.g. /blog
url: "http://www.edwardwoodcock.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/IAmFledge
  github: https://github.com/IAmFledge
  linkedin-square: https://linkedin.com/in/ecawoodcock
  facebook-official: https://facebook.com/edwardwoodcock
  google-plus-square: https://plus.google.com/u/0/+EdwardWoodcock-IAmFledge
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
sass:
 style: compressed
